const mongoose = require('mongoose')

const scheduleSchema = new mongoose.Schema(
{
    StatID: Number,
    TeamID: Number,
    PlayerID: Number,
    SeasonType: Number,
    Season: Number,
    Name: String,
    Team: String,
    Position: String,
    Started: Number,
    InjuryStatus: Number,
    GameID: Number,
    OpponentID: Number,
    Opponent: String,
    Day: Date,
    DateTime: Date,
    HomeOrAway: String,
    Games: Number,
    FantasyPoints: Number,
    Minutes: Number,
    Seconds: Number,
    FieldGoalsMade: Number,
    FieldGoalsAttempted: Number,
    FieldGoalsPercentage: Number,
    TwoPointersMade: Number,
    TwoPointersAttempted: Number,
    TwoPointersPercentage: Number,
    ThreePointersMade: Number,
    ThreePointersAttempted: Number,
    ThreePointersPercentage: Number,
    FreeThrowsMade: Number,
    FreeThrowsAttempted: Number,
    FreeThrowsPercentage: Number,
    OffensiveRebounds: Number,
    DefensiveRebounds: Number,
    Rebounds: Number,
    Assists: Number,
    Steals: Number,
    BlockedShots: Number,
    Turnovers: Number,
    PersonalFouls: Number,
    Points: Number,
    FantasyPointsFanDuel: Number,
    FantasyPointsDraftKings: Number,
    PlusMinus: Number,
    DoubleDoubles: Number,
    TripleDoubles: Number
})

module.exports = mongoose.model('Schedule', scheduleSchema)
