const mongoose = require("mongoose")

// Define the schema
const PlayerGameSchema = new mongoose.Schema({
  StatID: String,
  TeamID: String,
  PlayerID: String,
  SeasonType: String,
  Season: String,
  Name: String,
  Team: String,
  Position: String,
  Started: String,
  InjuryStatus: String,
  GameID: String,
  OpponentID: String,
  Opponent: String,
  Day: String,
  DateTime: String,
  HomeOrAway: String,
  Games: String,
  FantasyPoints: String,
  Minutes: String,
  Seconds: String,
  FieldGoalsMade: String,
  FieldGoalsAttempted: String,
  FieldGoalsPercentage: String,
  TwoPointersMade: String,
  TwoPointersAttempted: String,
  TwoPointersPercentage: String,
  ThreePointersMade: String,
  ThreePointersAttempted: String,
  ThreePointersPercentage: String,
  FreeThrowsMade: String,
  FreeThrowsAttempted: String,
  FreeThrowsPercentage: String,
  OffensiveRebounds: String,
  DefensiveRebounds: String,
  Rebounds: String,
  Assists: String,
  Steals: String,
  BlockedShots: String,
  Turnovers: String,
  PersonalFouls: String,
  Points: String,
  FantasyPointsFanDuel: String,
  FantasyPointsDraftKings: String,
  PlusMinus: String,
  DoubleDoubles: String,
  TripleDoubles: String,
})

PlayerGameSchema.index({ SeasonType: 1 })

module.exports = mongoose.model("PlayerGame", PlayerGameSchema)
